name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.*'
      - '.github/workflows/**'
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check

  test:
    name: Test
    needs: [style]

    strategy:
      matrix:
        build: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - build: nightly
            benches: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.build || 'stable' }}

      - name: Build debug
        run: cargo build --locked

      - name: Test
        run: cargo test --all-features

      - name: Test all benches
        if: matrix.benches
        run: cargo test --benches --all-features

  deploy-linux:
    name: deploy-${{ matrix.target }}
    permissions:
      contents: write
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, i686-unknown-linux-musl, arm-unknown-linux-gnueabi ,x86_64-unknown-linux-gnu ,x86_64-unknown-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        run: cargo install cross

      - name: Build target
        run: cross build --release --locked --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/poketex
          mkdir -p package
          cp target/${{ matrix.target }}/release/poketex package
          cp -r colorscripts package
          cd package
          tar czvf ../poketex-${{ matrix.target }}.tar.gz poketex colorscripts
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'poketex*'

  deploy-macos:
    name: deploy-${{ matrix.target }}
    permissions:
      contents: write
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: rustup target add aarch64-apple-darwin
        if: matrix.target == 'aarch64-apple-darwin'

      - name: Build target
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/poketex
          mkdir -p package
          cp target/${{ matrix.target }}/release/poketex package
          cp -r colorscripts package
          cd package
          tar czvf ../poketex-${{ matrix.target }}.tar.gz poketex colorscripts
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'poketex*'

  deploy-windows:
    name: deploy-${{ matrix.target }}
    permissions:
      contents: write
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build target
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/poketex
          mkdir -p package
          cp target/${{ matrix.target }}/release/poketex package
          cp -r colorscripts package
          cd package
          tar czvf ../poketex-${{ matrix.target }}.tar.gz poketex colorscripts
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'poketex*'
